services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
    - '127.0.0.1:4269:80'
    volumes:
      - './:/app'
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './:/app'
